### heartbeat check (public)
GET http://127.0.0.1:3000/heartbeat/1

### login 
POST http://127.0.0.1:3000/auth/login
Content-type: application/json; charset=utf8

{
    "username": "admin",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51"
}

### root (protected) 
GET http://127.0.0.1:3000
Content-type: application/json; charset=utf8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MTc2NDZhMC03NDM3LTQ4YTAtYmIwMy1hN2FhODMwZjhmODEiLCJqdGkiOiJBVDZlYzg0OTQ2LThiMTQtNGUxZS1hYjYwLTg5MjlhMmNmYzNkZSIsImlhdCI6MTcwMzU1MzU5NiwiZXhwIjoxNzAzNTU3MTk2fQ.N1TcQVnvSKlV4Flo9md9rBJ3RwwhQLLhKdNsHjr57p0


### refresh tokens
POST http://127.0.0.1:3000/auth/refresh
Content-type: application/json; charset=utf8

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKemRXSWlPaUkyTVRjMk5EWmhNQzAzTkRNM0xUUTRZVEF0WW1Jd015MWhOMkZoT0RNd1pqaG1PREVpTENKcWRHa2lPaUpCVkRnd056RTJNamc1TFdZeE1EQXRORGszTmkwNU16VXlMVEkzTnpJNE9EWTFNVFV6TkNJc0ltbGhkQ0k2TVRjd016VTFNell4T0N3aVpYaHdJam94TnpBek5UVTNNakU0ZlEuX1g3MmZfaFhTdjFlQ0REdTlQeEpXdnJjRy1nb3hDV3FWb01RbHd6UVh4OCIsImp0aSI6IlJUNDA0MzM1M2QtYWU2ZS00Mjg5LTg0OWQtMDExNjE2MGI0NWY3IiwiaWF0IjoxNzAzNTUzNjE4LCJleHAiOjE3MTEzMjk2MTh9.GkYM3zx8cODKwdakzPTMtdDNyghClg8l1RnaDrHS2kw

### logout 
POST http://127.0.0.1:3000/auth/logout
Content-type: application/json; charset=utf8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MTc2NDZhMC03NDM3LTQ4YTAtYmIwMy1hN2FhODMwZjhmODEiLCJqdGkiOiJBVDlhMmU2NmExLWUyYTctNGU0YS05ZWJjLTA2ZDM4OGEyMTFlNiIsImlhdCI6MTcwMzU1MzY3NCwiZXhwIjoxNzAzNTU3Mjc0fQ.unPzONm5R27G3cGHtOZU7VeAhQI25W05e8VVgVCEwAs

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKemRXSWlPaUkyTVRjMk5EWmhNQzAzTkRNM0xUUTRZVEF0WW1Jd015MWhOMkZoT0RNd1pqaG1PREVpTENKcWRHa2lPaUpCVkRsaE1tVTJObUV4TFdVeVlUY3ROR1UwWVMwNVpXSmpMVEEyWkRNNE9HRXlNVEZsTmlJc0ltbGhkQ0k2TVRjd016VTFNelkzTkN3aVpYaHdJam94TnpBek5UVTNNamMwZlEudW5Qek9ObTVSMjdHM2NHSHRPWlU3VmVBaFFJMjVXMDVlOFZWZ1ZDRXdBcyIsImp0aSI6IlJUYWY1MmQwMTItNTU2Mi00YzYyLThiYTktZTgwNWU3OWE5NTc2IiwiaWF0IjoxNzAzNTUzNjc0LCJleHAiOjE3MTEzMjk2NzR9.NYzMlYVpgb036dZCAu8yplA9Nou0ieuVVQjdpwXJT7I


### list users
GET http://127.0.0.1:3000/users

### get user
GET http://127.0.0.1:3000/users/617646a0-7437-48a0-bb03-a7aa830f8f81

### add a new user
POST http://127.0.0.1:3000/users
Content-type: application/json; charset=utf8

{
    "id": "917646a0-7437-48a0-bb03-a7aa830f8f81",
    "username": "admin2",
    "email": "admin2@admin.com",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51",
    "password_salt": "pjZKk6A8YtC8$9p&UIp62bv4PLwD7@dF"
}

### update user
PUT http://127.0.0.1:3000/users/917646a0-7437-48a0-bb03-a7aa830f8f81
Content-type: application/json; charset=utf8

{
    "id": "917646a0-7437-48a0-bb03-a7aa830f8f81",
    "username": "admin21",
    "email": "admin21@admin.com",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51",
    "password_salt": "pjZKk6A8YtC8$9p&UIp62bv4PLwD7@dF"
}

### delete user
DELETE http://127.0.0.1:3000/users/917646a0-7437-48a0-bb03-a7aa830f8f81

###