### heartbeat check (public)
GET http://127.0.0.1:3000/heartbeat/1

### login 
POST http://127.0.0.1:3000/auth/login HTTP/1.1
Content-type: application/json; charset=utf8

{
    "username": "admin",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51"
}

### root (protected) 
GET http://127.0.0.1:3000
Content-type: application/json; charset=utf8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MTc2NDZhMC03NDM3LTQ4YTAtYmIwMy1hN2FhODMwZjhmODEiLCJqdGkiOiJkNDVlZWY1MC0yNWQzLTRlODQtOGE5MC00N2QwNDg2ODM5YTgiLCJpYXQiOjE3MDM1MTIxMzYsImV4cCI6MTcwMzUxNTczNn0.X-BAEiNVnzS-6FnxFSJaETRSeAfCUQ9ClTsWKwA9SRc

### logout 
GET http://127.0.0.1:3000/auth/logout HTTP/1.1
Content-type: application/json; charset=utf8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MTc2NDZhMC03NDM3LTQ4YTAtYmIwMy1hN2FhODMwZjhmODEiLCJqdGkiOiJkNDVlZWY1MC0yNWQzLTRlODQtOGE5MC00N2QwNDg2ODM5YTgiLCJpYXQiOjE3MDM1MTIxMzYsImV4cCI6MTcwMzUxNTczNn0.X-BAEiNVnzS-6FnxFSJaETRSeAfCUQ9ClTsWKwA9SRc

### list users
GET http://127.0.0.1:3000/users

### get user
GET http://127.0.0.1:3000/users/617646a0-7437-48a0-bb03-a7aa830f8f81

### add a new user
POST http://127.0.0.1:3000/users
Content-type: application/json; charset=utf8

{
    "id": "917646a0-7437-48a0-bb03-a7aa830f8f81",
    "username": "admin2",
    "email": "admin2@admin.com",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51",
    "password_salt": "pjZKk6A8YtC8$9p&UIp62bv4PLwD7@dF"
}

### update user
PUT http://127.0.0.1:3000/users/917646a0-7437-48a0-bb03-a7aa830f8f81
Content-type: application/json; charset=utf8

{
    "id": "917646a0-7437-48a0-bb03-a7aa830f8f81",
    "username": "admin21",
    "email": "admin21@admin.com",
    "password_hash": "7c44575b741f02d49c3e988ba7aa95a8fb6d90c0ef63a97236fa54bfcfbd9d51",
    "password_salt": "pjZKk6A8YtC8$9p&UIp62bv4PLwD7@dF"
}

### delete user
DELETE http://127.0.0.1:3000/users/917646a0-7437-48a0-bb03-a7aa830f8f81

###